name: Unit Tests
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
jobs:
 unit-tests:
   runs-on: ubuntu-latest
   services:
    postgres:
        image: postgres:9.6
        env:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: thisisasecretpassword
            POSTGRES_DB: laravel
        ports:
            - 5432:5432
   env:
      DB_USERNAME: myuser
      DB_PASSWORD: thisisasecretpassword
      DB_HOST: localhost
      DB_DATABASE: laravel
   steps:
   - uses: actions/checkout@v2
   - name: Copy .env
     run: php -r "file_exists('.env') || copy('.env.example', '.env');"
   - name: Install dependencies
     uses: php-actions/composer@v5
     with:
        php_version: 7.4
        php_extensions: zip
   - name: Generate key
     run: php artisan key:generate
   - name: Run Migrations
     run: php artisan migrate
   - name: Execute unit tests
     run: vendor/bin/phpunit --coverage-clover=coverage.xml
   - uses: codecov/codecov-action@v1